const fs = require("fs");
const path = require("path");
const { Wallet } = require("ethers");

// Generates a fresh random EOA and persists it to contracts/.env so the
// Hardhat deploy task can pick it up. Refuses to overwrite an existing
// .env — re-keying a funded wallet by accident would be very bad.
function main() {
  const envPath = path.resolve(__dirname, "..", ".env");

  if (fs.existsSync(envPath)) {
    const existing = fs.readFileSync(envPath, "utf8");
    if (/DEPLOYER_PRIVATE_KEY=0x[0-9a-fA-F]{64}/.test(existing)) {
      console.error(
        `\n${envPath} already has a DEPLOYER_PRIVATE_KEY. Refusing to overwrite.\n` +
          `Delete it manually if you really want a new wallet.\n`,
      );
      process.exit(1);
    }
  }

  const wallet = Wallet.createRandom();
  const address = wallet.address;
  const privateKey = wallet.privateKey;

  const body =
    "# Generated by scripts/generate-wallet.cjs — DO NOT COMMIT\n" +
    "OG_RPC_URL=https://evmrpc-testnet.0g.ai\n" +
    `DEPLOYER_PRIVATE_KEY=${privateKey}\n` +
    "WIRE_ORACLE=\n";
  fs.writeFileSync(envPath, body, { mode: 0o600 });

  console.log("\nNew deployer wallet generated.\n");
  console.log("  Address    :", address);
  console.log("  Private key:", privateKey);
  console.log("  Saved to   :", envPath);
  console.log("\nNext steps:");
  console.log("  1. Fund the address at https://faucet.0g.ai (0G Galileo testnet OG).");
  console.log("  2. Verify the balance, then run: npm run deploy");
  console.log("");
}

main();
